name = "chat-backend-workers"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[env.production.vars]
# OPENAI_API_KEY = "your-openai-api-key-here"

[env.development.vars]
# OPENAI_API_KEY = "your-openai-api-key-here"

# 设置环境变量（使用 wrangler secret put 命令）
# wrangler secret put OPENAI_API_KEY